language: node_js
node_js:
  - "10"

script: npm run build
branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: dist
  target-branch: gh-pages
  on:
    branch: master
